ROOMS = [
    {"id": "101", "andar": 1, "capacidade": 80, "tipo": "Auditório", "recursos": ["projetor", "som"], "acessivel": True},
    {"id": "102", "andar": 1, "capacidade": 20, "tipo": "Reunião", "recursos": ["tv"], "acessivel": False},
    {"id": "103", "andar": 1, "capacidade": 12, "tipo": "Reunião", "recursos": [], "acessivel": False},
    {"id": "104", "andar": 1, "capacidade": 45, "tipo": "Treinamento", "recursos": ["projetor"], "acessivel": False},
    {"id": "201", "andar": 2, "capacidade": 15, "tipo": "Reunião", "recursos": [], "acessivel": False},
    {"id": "202", "andar": 2, "capacidade": 30, "tipo": "Reunião", "recursos": ["tv"], "acessivel": True},
    {"id": "203", "andar": 2, "capacidade": 8, "tipo": "Reunião", "recursos": [], "acessivel": False},
    {"id": "204", "andar": 2, "capacidade": 25, "tipo": "Laboratório", "recursos": ["computadores"], "acessivel": False},
    {"id": "301", "andar": 3, "capacidade": 20, "tipo": "Reunião", "recursos": [], "acessivel": True},
    {"id": "302", "andar": 3, "capacidade": 50, "tipo": "Projeto", "recursos": ["projetor"], "acessivel": False},
    {"id": "303", "andar": 3, "capacidade": 10, "tipo": "Reunião", "recursos": [], "acessivel": False},
    {"id": "304", "andar": 3, "capacidade": 35, "tipo": "Projeto", "recursos": [], "acessivel": False},
    {"id": "401", "andar": 4, "capacidade": 18, "tipo": "Reunião", "recursos": [], "acessivel": False},
    {"id": "402", "andar": 4, "capacidade": 60, "tipo": "Projeto", "recursos": ["projetor", "tv"], "acessivel": False},
    {"id": "403", "andar": 4, "capacidade": 12, "tipo": "Reunião", "recursos": [], "acessivel": True},
    {"id": "404", "andar": 4, "capacidade": 25, "tipo": "Reunião", "recursos": [], "acessivel": False},
    {"id": "501", "andar": 5, "capacidade": 22, "tipo": "Reunião", "recursos": [], "acessivel": False},
    {"id": "502", "andar": 5, "capacidade": 15, "tipo": "Reunião", "recursos": [], "acessivel": False},
    {"id": "503", "andar": 5, "capacidade": 30, "tipo": "Treinamento", "recursos": [], "acessivel": True},
    {"id": "504", "andar": 5, "capacidade": 40, "tipo": "Projeto", "recursos": ["projetor"], "acessivel": False},
    {"id": "601", "andar": 6, "capacidade": 28, "tipo": "Reunião", "recursos": [], "acessivel": False},
    {"id": "602", "andar": 6, "capacidade": 14, "tipo": "Reunião", "recursos": [], "acessivel": False},
    {"id": "603", "andar": 6, "capacidade": 55, "tipo": "Auditório", "recursos": ["tv", "projetor"], "acessivel": True},
    {"id": "604", "andar": 6, "capacidade": 20, "tipo": "Laboratório", "recursos": ["computadores"], "acessivel": False},
    {"id": "701", "andar": 7, "capacidade": 50, "tipo": "Projeto", "recursos": ["projetor"], "acessivel": False},
    {"id": "702", "andar": 7, "capacidade": 20, "tipo": "Reunião", "recursos": [], "acessivel": False},
    {"id": "703", "andar": 7, "capacidade": 10, "tipo": "Reunião", "recursos": [], "acessivel": False},
    {"id": "704", "andar": 7, "capacidade": 45, "tipo": "Projeto", "recursos": ["projetor"], "acessivel": True},
    {"id": "801", "andar": 8, "capacidade": 16, "tipo": "Reunião", "recursos": [], "acessivel": False},
    {"id": "802", "andar": 8, "capacidade": 32, "tipo": "Reunião", "recursos": ["tv"], "acessivel": False},
    {"id": "803", "andar": 8, "capacidade": 8, "tipo": "Reunião", "recursos": [], "acessivel": False},
    {"id": "804", "andar": 8, "capacidade": 24, "tipo": "Projeto", "recursos": [], "acessivel": False},
    {"id": "901", "andar": 9, "capacidade": 20, "tipo": "Reunião", "recursos": [], "acessivel": False},
    {"id": "902", "andar": 9, "capacidade": 14, "tipo": "Reunião", "recursos": [], "acessivel": False},
    {"id": "903", "andar": 9, "capacidade": 60, "tipo": "Auditório", "recursos": ["projetor", "tv"], "acessivel": True},
    {"id": "904", "andar": 9, "capacidade": 10, "tipo": "Reunião", "recursos": [], "acessivel": False},
]

SECTORS = [
    {"id": "tecnologia", "nome": "Tecnologia", "coordenador": "Marina Alves"},
    {"id": "rh", "nome": "Recursos Humanos", "coordenador": "Bruno Castro"},
    {"id": "financeiro", "nome": "Financeiro", "coordenador": "Renata Souza"},
    {"id": "juridico", "nome": "Jurídico", "coordenador": "Paulo Nogueira"},
    {"id": "marketing", "nome": "Marketing", "coordenador": "Camila Duarte"},
    {"id": "comercial", "nome": "Comercial", "coordenador": "Diego Ramos"},
    {"id": "operacoes", "nome": "Operações", "coordenador": "Fernanda Lima"},
    {"id": "ped", "nome": "Pesquisa e Desenvolvimento", "coordenador": "Igor Teixeira"},
]

TEAMS = [
    {"id": "dev_backend", "nome": "Dev Backend", "setor_id": "tecnologia", "tamanho": 24, "prioridade": "alta", "grupo_proximidade": "tech"},
    {"id": "dev_frontend", "nome": "Dev Frontend", "setor_id": "tecnologia", "tamanho": 18, "prioridade": "media", "grupo_proximidade": "tech"},
    {"id": "infraestrutura", "nome": "Infraestrutura", "setor_id": "tecnologia", "tamanho": 10, "prioridade": "baixa"},
    {"id": "recrutamento", "nome": "Recrutamento", "setor_id": "rh", "tamanho": 14, "prioridade": "media"},
    {"id": "treinamento", "nome": "Treinamento", "setor_id": "rh", "tamanho": 28, "prioridade": "alta"},
    {"id": "folha", "nome": "Folha de Pagamento", "setor_id": "rh", "tamanho": 9, "prioridade": "baixa"},
    {"id": "contabilidade", "nome": "Contabilidade", "setor_id": "financeiro", "tamanho": 20, "prioridade": "alta"},
    {"id": "controladoria", "nome": "Controladoria", "setor_id": "financeiro", "tamanho": 15, "prioridade": "media"},
    {"id": "tesouraria", "nome": "Tesouraria", "setor_id": "financeiro", "tamanho": 8, "prioridade": "baixa"},
    {"id": "contratos", "nome": "Contratos", "setor_id": "juridico", "tamanho": 12, "prioridade": "alta"},
    {"id": "compliance", "nome": "Compliance", "setor_id": "juridico", "tamanho": 9, "prioridade": "media"},
    {"id": "digital", "nome": "Marketing Digital", "setor_id": "marketing", "tamanho": 16, "prioridade": "media"},
    {"id": "conteudo", "nome": "Conteúdo", "setor_id": "marketing", "tamanho": 11, "prioridade": "baixa"},
    {"id": "eventos", "nome": "Eventos", "setor_id": "marketing", "tamanho": 22, "prioridade": "alta"},
    {"id": "vendas_internas", "nome": "Vendas Internas", "setor_id": "comercial", "tamanho": 35, "prioridade": "alta"},
    {"id": "key_accounts", "nome": "Key Accounts", "setor_id": "comercial", "tamanho": 14, "prioridade": "media"},
    {"id": "pre_vendas", "nome": "Pré-vendas", "setor_id": "comercial", "tamanho": 19, "prioridade": "baixa"},
    {"id": "logistica", "nome": "Logística", "setor_id": "operacoes", "tamanho": 30, "prioridade": "media"},
    {"id": "equipe_delta", "nome": "Equipe Delta", "setor_id": "operacoes", "tamanho": 92, "prioridade": "alta"},
    {"id": "suporte", "nome": "Suporte", "setor_id": "operacoes", "tamanho": 17, "prioridade": "baixa"},
    {"id": "pesquisa", "nome": "Pesquisa", "setor_id": "ped", "tamanho": 26, "prioridade": "alta", "req_equip": ["computadores"]},
    {"id": "inovacao", "nome": "Inovação", "setor_id": "ped", "tamanho": 13, "prioridade": "media"},
    {"id": "prototipos", "nome": "Protótipos", "setor_id": "ped", "tamanho": 20, "prioridade": "baixa", "req_equip": ["computadores"]},
]

CONSTRAINTS = [
    {"id": "c1", "tipo": "acessibilidade_obrigatoria", "alvo": "treinamento", "valor": None, "descricao": 'Equipe "Treinamento" (RH) exige sala acessível'},
    {"id": "c2", "tipo": "equipamento_obrigatorio", "alvo": "pesquisa", "valor": ["computadores"], "descricao": 'Equipe "Pesquisa" (P&D) exige sala com computadores'},
    {"id": "c3", "tipo": "equipamento_obrigatorio", "alvo": "prototipos", "valor": ["computadores"], "descricao": 'Equipe "Protótipos" (P&D) exige sala com computadores'},
    {"id": "c4", "tipo": "sala_reservada", "alvo": "juridico", "valor": "901", "descricao": "Sala 901 reservada para o setor Jurídico"},
    {"id": "c5", "tipo": "andar_permitido", "alvo": "comercial", "valor": [3, 4], "descricao": "Setor Comercial deve ficar nos andares 3 ou 4"},
    {"id": "c6", "tipo": "proximidade", "alvo": None, "valor": "tech", "descricao": "Dev Backend e Dev Frontend devem ficar no mesmo andar"},
    {"id": "c7", "tipo": "capacidade_minima", "alvo": None, "valor": 8, "descricao": "Nenhuma sala com capacidade inferior a 8 pode ser considerada"},
    {"id": "c8", "tipo": "setores_nao_compartilham", "alvo": None, "valor": ["juridico", "comercial"], "descricao": "Jurídico e Comercial não podem compartilhar o mesmo andar"},
]


